filebeat.inputs:
  - type: filestream
    id: express-backend
    enabled: true
    paths:
      - /app-logs/*.log
    ignore_older: 24h
    fields:
      service: backend-express
      component: express
      environment: dev
    fields_under_root: true
    # parsers:
    #   - ndjson:
    #       overwrite_keys: true
    #       add_error_key: true
    #       expand_keys: true

  - type:
    id: express-database
    enabled: true
    paths:
      - /var/log/mysql/*.log
    fields:
      service: backend-express
      component: mysql
      environment: dev
    fields_under_root: true

output.logstash:
  hosts: ["host.docker.internal:5044"]
