volumes:
  mysql_data:

services:
  backend:
    build: ../backend
    env_file:
      - ../backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ../backend/logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - recipe-network

  frontend:
    build: ../frontend
    ports:
      - "5173:5173"
    networks:
      - recipe-network

  mysql:
    image: mysql:8.0
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--log-error=/var/log/mysql/error.log",
        "--log-error-verbosity=2",
        "--slow_query_log=ON",
        "--slow_query_log_file=/var/log/mysql/slow.log",
        "--long_query_time=1"
      ]
    environment:
      MYSQL_ROOT_PASSWORD: Deep@2004
      MYSQL_DATABASE: recipe_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ../backend/logs/my-sql/:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - recipe-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    user: root
    environment:
      LOGSTASH_HOST: ${LOGSTASH_HOST:-host.docker.internal}
      LOGSTASH_PORT: ${LOGSTASH_PORT:-5044}
    volumes:
      - ../backend/logs:/app-logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ../backend/logs/my-sql/:/var/log/mysql
    command: ["filebeat", "-e", "--strict.perms=false"]
    depends_on:
      - backend
    networks:
      - recipe-network

networks:
  recipe-network:
    external: true
    name: elk-net